<hr>
<h1><center>Pandas Series</center></h1>
<hr>

In [1]:
import pandas as pd

#### Creating a serie with pandas

In [2]:
ds = pd.Series([1,4,6,7,8])
ds

0    1
1    4
2    6
3    7
4    8
dtype: int64

In [3]:
type(ds)

pandas.core.series.Series

#### Converting to a list

In [4]:
ds.tolist()

[1, 4, 6, 7, 8]

#### Adding

In [5]:
ds2 = pd.Series([1, 3, 5, 7, 5])

In [6]:
ds + ds2

0     2
1     7
2    11
3    14
4    13
dtype: int64

#### Substracting

In [7]:
ds - ds2

0    0
1    1
2    1
3    0
4    3
dtype: int64

#### Multiplying

In [8]:
ds * ds2

0     1
1    12
2    30
3    49
4    40
dtype: int64

#### Dividing

In [9]:
ds / ds2

0    1.000000
1    1.333333
2    1.200000
3    1.000000
4    1.600000
dtype: float64

#### Comparing

In [10]:
ds == ds2

0     True
1    False
2    False
3     True
4    False
dtype: bool

In [11]:
ds >= ds2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [12]:
ds <= ds2

0     True
1    False
2    False
3     True
4    False
dtype: bool

In [13]:
ds != ds2

0    False
1     True
2     True
3    False
4     True
dtype: bool

#### Converting to a pd.series

In [14]:
d = {'a': 2, 'b': 4, 'c':6, 'd':8}

In [15]:
ds = pd.Series(d)
ds

a    2
b    4
c    6
d    8
dtype: int64

In [16]:
import numpy as np

array = np.array([2,4,6,8])
ds = pd.Series(array)
ds

0    2
1    4
2    6
3    8
dtype: int32

In [17]:
lis = ds.values.tolist()
lis

[2, 4, 6, 8]

#### The first column of a dataset as a pd.Series

In [18]:
# import some data to play with
from sklearn import datasets

iris = datasets.load_iris()
df = iris.data[:, :2]  # we only take the first two features.
df = pd.DataFrame(df)

In [19]:
Serie = df.iloc[:,[1]]
Serie.head(5)

1
0  3.5
1  3.0
2  3.2
3  3.1
4  3.6

In [20]:
type(Serie)

pandas.core.frame.DataFrame

#### Sorting

In [21]:
s = pd.Series([8,4,6,1,6])

In [22]:
s_sorted = s.sort_values()
s_sorted

3    1
1    4
2    6
4    6
0    8
dtype: int64

#### Adding more elements to a series

In [23]:
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
s2 = pd.Series(['500', 'php'])

In [24]:
new = pd.concat((s1,s2))
new

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

In [25]:
conc = pd.concat((s1,s2)).reset_index()
conc

index       0
0      0     100
1      1     200
2      2  python
3      3  300.12
4      4     400
5      0     500
6      1     php

#### Subsets

In [26]:
s = pd.Series([1,2,3,4,5,6,7,8,9,10])
s[s<=5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

#### Mean and standar deviation

In [27]:
s.mean()

5.5

In [28]:
s.std()

3.0276503540974917

#### Union and interception

In [29]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])
s2 = pd.Series([2,4,6,8,10])

In [30]:
np.intersect1d(s1,s2)

array([ 2,  4,  6,  8, 10], dtype=int64)

In [31]:
s_union = pd.Series(np.union1d(s1, s2))
s_union

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [32]:
s_intercept = pd.Series(np.intersect1d(s1, s2))
s_intercept

0     2
1     4
2     6
3     8
4    10
dtype: int64

#### The frequency of each unique value

In [33]:
serie = pd.Series(np.random.randint(0,10, size=100))
serie.head(5)

0    2
1    0
2    3
3    1
4    7
dtype: int32

In [34]:
serie.value_counts()

0    14
6    14
2    13
3    13
8    12
1    10
4    10
7     5
9     5
5     4
dtype: int64

In [35]:
serie.value_counts().head(1)  # The most frequent value

0    14
dtype: int64

#### The positions of the values that are multiple of three

In [36]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1, 100, 100))


result1 = np.where(num_series % 3==0)
result1

(array([ 5,  7, 10, 12, 15, 23, 24, 25, 26, 28, 29, 31, 36, 41, 43, 44, 45,
        49, 50, 54, 55, 58, 60, 61, 69, 72, 77, 78, 91, 92, 94, 95, 96, 98],
       dtype=int64),)

In [37]:
result2 = []

for i,j in enumerate(num_series):
    if j%3==0:
        result2.append(i)

In [38]:
result2 = np.array(result2)
result2

array([ 5,  7, 10, 12, 15, 23, 24, 25, 26, 28, 29, 31, 36, 41, 43, 44, 45,
       49, 50, 54, 55, 58, 60, 61, 69, 72, 77, 78, 91, 92, 94, 95, 96, 98])

In [39]:
serie = pd.Series(np.random.randint(1,10,50))

In [40]:
np.where(serie%5==0)

(array([22, 29, 31, 35, 38], dtype=int64),)

In [41]:
a = np.where(serie%3==0)
b = np.where(serie%5==0)
a,b

((array([ 1,  3,  4,  7,  8, 10, 13, 15, 17, 21, 26, 32, 33, 37, 40, 42, 45,
         49], dtype=int64),),
 (array([22, 29, 31, 35, 38], dtype=int64),))

In [42]:
result = pd.Series(np.union1d(a,b))

In [43]:
result

0      1
1      3
2      4
3      7
4      8
5     10
6     13
7     15
8     17
9     21
10    22
11    26
12    29
13    31
14    32
15    33
16    35
17    37
18    38
19    40
20    42
21    45
22    49
dtype: int64

In [44]:
element_pos = [0, 2, 6, 11, 21]
serie.take(element_pos)

0     8
2     4
6     7
11    1
21    9
dtype: int32

In [45]:
serie.take([2,4,6])

2    4
4    9
6    7
dtype: int32

#### Calculate the number of elements (words)

In [46]:
series1 = pd.Series(['Python', 'Pandas', 'Numpy', 'Scipy'])

result = series1.map(lambda x: len(x))
result

0    6
1    6
2    5
3    5
dtype: int64

#### Capitalize the first and last word

In [47]:
series1 = pd.Series(['Python', 'Pandas', 'Numpy', 'Scipy'])

series1.map(lambda x: x[0].upper()+x[1:-1]+x[-1].upper())

0    PythoN
1    PandaS
2     NumpY
3     ScipY
dtype: object

#### Convert a series of date strings to a timeseries

In [48]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])

pd.to_datetime(date_series)

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

### Distance between two series

In [49]:
x = pd.Series(np.random.randint(1,10,10))
y = pd.Series(np.random.randint(1,10,10))

print(np.linalg.norm(x-y))

10.099504938362077
